# Generated by Django 4.1.1 on 2022-09-28 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savebot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramusers',
            name='credits',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='telegramusers',
            name='is_premium',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='telegramusers',
            name='language_code',
            field=models.CharField(default=0, max_length=10, verbose_name='TIL'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='telegramusers',
            name='telegram_id',
            field=models.BigIntegerField(default=0, unique=True),
            preserve_default=False,
        ),
    ]
