# Generated by Django 4.1.1 on 2022-09-29 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savebot', '0002_telegramusers_credits_telegramusers_is_premium_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apicalls',
            options={'verbose_name': 'Kanallar', 'verbose_name_plural': 'Kanallar'},
        ),
        migrations.AlterField(
            model_name='apicalls',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='channels',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name="QO'SHILGAN VAQTI"),
        ),
        migrations.AlterField(
            model_name='telegramusers',
            name='is_premium',
            field=models.BooleanField(default=False, verbose_name='PREMIUM'),
        ),
        migrations.AlterField(
            model_name='telegramusers',
            name='joined_date',
            field=models.DateField(auto_now_add=True, verbose_name="QO'SHILGAN VAQTI"),
        ),
    ]
