# Generated by Django 4.1.1 on 2022-09-29 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savebot', '0003_alter_apicalls_options_alter_apicalls_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apicalls',
            options={'verbose_name': "API so'rovlar", 'verbose_name_plural': "API so'rovlar"},
        ),
        migrations.AlterField(
            model_name='telegramusers',
            name='credits',
            field=models.IntegerField(default=10, verbose_name='KREDITLAR'),
        ),
    ]
