# Generated by Django 4.1.1 on 2022-10-03 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savebot', '0005_invitelink'),
    ]

    operations = [
        migrations.AddField(
            model_name='channels',
            name='invite_link',
            field=models.CharField(default=False, max_length=255, verbose_name='TASHRIF LINKI'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='channels',
            name='status',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
